### ISSUE TITLE
AttributeError: 'module' object has no attribute 'urlencode'

### ISSUE THREAD

**Issue by galets** [subuser-security/subuser#193]
I am at commit 6e35124d8d842afe383f32c0da788d70dc5d0edb :

	$ subuser subuser add libx11 libx11@default

	Adding subuser libx11 libx11@default
	Verifying subuser configuration.
	Verifying registry consistency...
	Unregistering any non-existant installed images.
	Checking if images need to be updated or installed...
	Installing libx11 ...
	Traceback (most recent call last):
	  File "/usr/local/share/subuser/logic/subuserCommands/subuser.py", line 184, in <module>
		subuser(sys.argv[1:])
	  File "/usr/local/share/subuser/logic/subuserCommands/subuser.py", line 169, in subuser
		subuserlib.subuser.add(user,name,imageSourceId)
	  File "/usr/local/share/subuser/logic/subuserlib/subuser.py", line 24, in add
		subuserlib.verify.verify(user)
	  File "/usr/local/share/subuser/logic/subuserlib/verify.py", line 32, in verify
		ensureImagesAreInstalledAndUpToDate(user)
	  File "/usr/local/share/subuser/logic/subuserlib/verify.py", line 49, in ensureImagesAreInstalledAndUpToDate
		subuserlib.install.ensureSubuserImageIsInstalledAndUpToDate(subuser)
	  File "/usr/local/share/subuser/logic/subuserlib/install.py", line 172, in ensureSubuserImageIsInstalledAndUpToDate
		subuser.setImageId(installLineage([imageSource]+sourceLineage,parent=parentId))
	  File "/usr/local/share/subuser/logic/subuserlib/install.py", line 114, in installLineage
		parent = installImage(imageSource,parent=parent)
	  File "/usr/local/share/subuser/logic/subuserlib/install.py", line 76, in installImage
		imageId = installFromSubuserImagefile(imageSource,useCache=useCache,parent=parent)
	  File "/usr/local/share/subuser/logic/subuserlib/install.py", line 64, in installFromSubuserImagefile
		imageId = imageSource.getUser().getDockerDaemon().build(directoryWithDockerfile=dockerImageDir,rm=True,useCache=useCache,dockerfile=dockerFileContents)
	  File "/usr/local/share/subuser/logic/subuserlib/classes/dockerDaemon.py", line 132, in build
		queryParametersString = urllib.urlencode(queryParameters)
	AttributeError: 'module' object has no attribute 'urlencode'

**Comment by timthelion** [comment]
Sorry about this. This was a python3 incompatibility in some code which was previously not covered by the test suit (the part of the code that communicates directly with the Docker daemon and is therefor the hardest to test. I have written some more mock up code to increase coverage and beleive the bug to now be fixed. Please report back if you are still experiencing problems.
