### ISSUE TITLE
TypeError: Can't convert 'bytes' object to str implicitly

### ISSUE THREAD

**Issue by galets** [subuser-security/subuser#194]
arch linux. On commit d88cb618e7f9734b5ff5a060449858ddfd638017

	$ subuser subuser add libx11 libx11@default
	Adding subuser libx11 libx11@default
	Verifying subuser configuration.
	Verifying registry consistency...
	Unregistering any non-existant installed images.
	Checking if images need to be updated or installed...
	Installing libx11 ...
	Traceback (most recent call last):
	  File "/usr/local/share/subuser/logic/subuserCommands/subuser.py", line 200, in <module>
		subuser(sys.argv[1:])
	  File "/usr/local/share/subuser/logic/subuserCommands/subuser.py", line 185, in subuser
		subuserlib.subuser.add(user,name,imageSourceId)
	  File "/usr/local/share/subuser/logic/subuserlib/subuser.py", line 24, in add
		subuserlib.verify.verify(user)
	  File "/usr/local/share/subuser/logic/subuserlib/verify.py", line 32, in verify
		ensureImagesAreInstalledAndUpToDate(user)
	  File "/usr/local/share/subuser/logic/subuserlib/verify.py", line 49, in ensureImagesAreInstalledAndUpToDate
		subuserlib.install.ensureSubuserImageIsInstalledAndUpToDate(subuser)
	  File "/usr/local/share/subuser/logic/subuserlib/install.py", line 172, in ensureSubuserImageIsInstalledAndUpToDate
		subuser.setImageId(installLineage([imageSource]+sourceLineage,parent=parentId))
	  File "/usr/local/share/subuser/logic/subuserlib/install.py", line 114, in installLineage
		parent = installImage(imageSource,parent=parent)
	  File "/usr/local/share/subuser/logic/subuserlib/install.py", line 76, in installImage
		imageId = installFromSubuserImagefile(imageSource,useCache=useCache,parent=parent)
	  File "/usr/local/share/subuser/logic/subuserlib/install.py", line 64, in installFromSubuserImagefile
		imageId = imageSource.getUser().getDockerDaemon().build(directoryWithDockerfile=dockerImageDir,rm=True,useCache=useCache,dockerfile=dockerFileContents)
	  File "/usr/local/share/subuser/logic/subuserlib/classes/dockerDaemon.py", line 167, in build
		output = readAndPrintStreamingBuildStatus(self.getUser(),response)
	  File "/usr/local/share/subuser/logic/subuserlib/classes/dockerDaemon.py", line 65, in readAndPrintStreamingBuildStatus
		jsonSegment += byte
	TypeError: Can't convert 'bytes' object to str implicitly

**Comment by timthelion** [comment]
Argh!!!

**Comment by timthelion** [comment]
;) :P

**Comment by timthelion** [comment]
This is hopefully fixed now. I had to actually install python3 and test it out. It took me a while to fix everything, partially because I was buisy and partially because of some bugs in the interation of tar and tempfile. You can check out the code if you want to know what I mean.
