### ISSUE TITLE
Unable to start subuser, with either stable or the git version

### ISSUE THREAD

**Issue by csterritt** [subuser-security/subuser#277]
Hi -- trying to try out subuser on a Ubuntu 14.04.3 machine.

The install works fine either way, but when I try to run `subuser list available` I see:

    $ subuser list available
    Traceback (most recent call last):
      File "/usr/local/bin/subuser-list.py", line 139, in <module>
        list(sys.argv[1:])
      File "/usr/local/bin/subuser-list.py", line 60, in list
        reposToList = user.getRegistry().getRepositories().keys()
      File "/usr/local/lib/python3.4/dist-packages/subuserlib/classes/registry.py", line 52, in getRepositories
        self.__repositories = repositories.Repositories(self.getUser())
      File "/usr/local/lib/python3.4/dist-packages/subuserlib/classes/repositories.py", line 28, in __init__
        self.reloadRepositoryLists()
      File "/usr/local/lib/python3.4/dist-packages/subuserlib/classes/repositories.py", line 50, in reloadRepositoryLists
        repositoryStates = self._loadRepositoryStates()
      File "/usr/local/lib/python3.4/dist-packages/subuserlib/classes/repositories.py", line 91, in _loadRepositoryStates
        if "repository-states.json" in gitFileStructure.lsFiles("./"):
      File "/usr/local/lib/python3.4/dist-packages/subuserlib/classes/gitRepository.py", line 194, in lsFiles
        return list(set(self.ls(subfolder)) - set(self.lsFolders(subfolder)))
      File "/usr/local/lib/python3.4/dist-packages/subuserlib/classes/gitRepository.py", line 177, in ls
        items = self.lsTree(subfolder,extraArgs)
      File "/usr/local/lib/python3.4/dist-packages/subuserlib/classes/gitRepository.py", line 154, in lsTree
        (returncode,output) = self.getRepository().runCollectOutput(["ls-tree"]+args)
      File "/usr/local/lib/python3.4/dist-packages/subuserlib/classes/gitRepository.py", line 62, in runCollectOutput
        raise Exception(stderr)
    Exception: fatal: Not a valid object name master

What am I doing wrong?  thanks!

**Comment by timthelion** [comment]
Hi,

Did you not have git settup the first time you ran subuser? If it fails
to initialize, then it can get into a weird state where it will not run
properly. In any case, the solution should be deleting your ~/.subuser
directory and trying again. However, I should fix this so that it
doesn't crash in such an ugly way.

Tim

**Comment by timthelion** [comment]
I just pushed a fix that might make it so that subuser is somewhat more
inteligent about this situation...

**Comment by csterritt** [comment]
Oooh, did the `rm -rf .subuser`, then a `subuser list available` worked perfectly!  Thanks!

**Comment by whoo** [comment]
Hi Guys,
This Problem is still present.

```rm -rf ~/.subuser``` then ```subuser list available```

```
Initial commit.
Cloning repository default from https://github.com/subuser-security/subuser-default-repository.git
Clonage dans '/home/domi/.subuser/repositories/default'...
remote: Counting objects: 2668, done.
remote: Total 2668 (delta 0), reused 0 (delta 0), pack-reused 2668
Réception d'objets: 100% (2668/2668), 334.88 KiB | 0 bytes/s, fait.
Résolution des deltas: 100% (1535/1535), fait.
Traceback (most recent call last):
  File "/usr/local/Wizz/subuser/bin//subuser", line 52, in <module>
    command(sys.argv[2:])
  File "/usr/local/Wizz/subuser/logic/subuserlib/builtInCommands/list.py", line 57, in runCommand
    reposToList = user.registry.repositories.keys()
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/user.py", line 70, in registry
    self.__registry.ensureGitRepoInitialized()
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/registry.py", line 63, in ensureGitRepoInitialized
    self.commit("Initial commit.",_no_lock_needed = True)
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/registry.py", line 106, in commit
    self.repositories.save()
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/registry.py", line 52, in repositories
    self.__repositories = repositories.Repositories(self.user)
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/repositories.py", line 28, in __init__
    self.reloadRepositoryLists()
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/repositories.py", line 76, in reloadRepositoryLists
    self.systemRepositories = loadRepositoryDict(subuserlib.loadMultiFallbackJsonConfigFile.getConfig(self.systemRepositoryListPaths))
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/repositories.py", line 74, in loadRepositoryDict
    repositories[repoName] = Repository(self.user,name=repoName,gitOriginURI=gitOriginURI,gitCommitHash=gitCommitHash,temporary=temporary,sourceDir=sourceDir)
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/repository.py", line 35, in __init__
    self.updateSources(initialUpdate=True)
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/repository.py", line 193, in updateSources
    if self.updateGitCommitHash():
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/repository.py", line 233, in updateGitCommitHash
    if self.gitRepository.getFileStructureAtCommit("master").exists("./.subuser.json"):
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/fileStructure.py", line 61, in exists
    return self._exists(path)
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/gitRepository.py", line 239, in _exists
    for object in self.lsTree():
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/gitRepository.py", line 169, in lsTree
    (returncode,output) = self.gitRepository.runCollectOutput(["ls-tree"]+args)
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/gitRepository.py", line 91, in runCollectOutput
    raise GitException(stderr)
subuserlib.classes.gitRepository.GitException: fatal: Not a valid object name master
```
