### ISSUE TITLE
Starting xpra client...

### ISSUE THREAD

**Issue by ehsanmostajeran** [subuser-security/subuser#288]
I get this error when I run vlc@default.

`Starting xpra server...
Starting xpra client...
Traceback (most recent call last):
  File "/usr/local/bin/subuser", line 5, in <module>
    pkg_resources.run_script('subuser==0.5.6', 'subuser')
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 55, in execfile
    exec(compile(open(fn).read(), fn, 'exec'), globs, locs)
  File "/usr/local/lib/python3.4/dist-packages/subuser-0.5.6-py3.4.egg/EGG-INFO/scripts/subuser", line 28, in <module>
    command(sys.argv[2:])
  File "/usr/local/lib/python3.4/dist-packages/subuser-0.5.6-py3.4.egg/subuserlib/builtInCommands/run.py", line 77, in runCommand
    runtime.run(argParser.subuserArgs)
  File "/usr/local/lib/python3.4/dist-packages/subuser-0.5.6-py3.4.egg/subuserlib/classes/subuserSubmodules/run/runtime.py", line 310, in run
    return reallyRun()
  File "/usr/local/lib/python3.4/dist-packages/subuser-0.5.6-py3.4.egg/subuserlib/classes/subuserSubmodules/run/runtime.py", line 282, in reallyRun
    self.getSubuser().getX11Bridge().addClient()
  File "/usr/local/lib/python3.4/dist-packages/subuser-0.5.6-py3.4.egg/subuserlib/classes/service.py", line 95, in addClient
    serviceStatus = self.start(serviceStatus)
  File "/usr/local/lib/python3.4/dist-packages/subuser-0.5.6-py3.4.egg/subuserlib/classes/subuserSubmodules/run/x11Bridge.py", line 245, in start
    (clientContainer, clientProcess) = clientRuntime.run(args=clientArgs)
  File "/usr/local/lib/python3.4/dist-packages/subuser-0.5.6-py3.4.egg/subuserlib/classes/subuserSubmodules/run/runtime.py", line 310, in run
    return reallyRun()
  File "/usr/local/lib/python3.4/dist-packages/subuser-0.5.6-py3.4.egg/subuserlib/classes/subuserSubmodules/run/runtime.py", line 269, in reallyRun
    self.setupXauth()
  File "/usr/local/lib/python3.4/dist-packages/subuser-0.5.6-py3.4.egg/subuserlib/classes/subuserSubmodules/run/runtime.py", line 231, in setupXauth
    subuserlib.subprocessExtras.call(self.getUser().getEndUser().getSudoArgs()+["xauth","extract",".Xauthority",self.getEnvironment()["DISPLAY"]],cwd=self.getXautorityDirPath())
  File "/usr/lib/python3.4/os.py", line 633, in __getitem__
    raise KeyError(key) from None
KeyError: 'DISPLAY'
`

**Comment by timthelion** [comment]
Uff, what OS?

**Comment by zackp30** [comment]
What does `echo $DISPLAY` return?

**Comment by ehsanmostajeran** [comment]
Ubuntu

**Comment by timthelion** [comment]
Are you doing this via SSH or in vagrant? As zackp30 asked, what does `echo $DISPLAY` show?

**Comment by ehsanmostajeran** [comment]
It is not run by Vagrant. I have removed and added vlc@default again. Same error.
echo $DISPLAY doesn't show anything.

**Comment by timthelion** [comment]
I'm not currently using ubuntu, and it is very unsually that $DISPLAY is
not set. It occures to me whether you're running subuser as root, but
you are logged in as a different user?

**Comment by ehsanmostajeran** [comment]
sorry for late reply, yes user is root, alright i will test it with different user.

**Comment by timthelion** [comment]
you need to be the same user as the one you logged in as when you
started the X11 session. That's the main thing.
