### ISSUE TITLE
Crash on remove-old-images

### ISSUE THREAD

**Issue by timthelion** [subuser-security/subuser#304]
````
> ./subuser remove-old-images
Traceback (most recent call last):
  File "./subuser", line 52, in <module>
    command(sys.argv[2:])
  File "/home/timothy/current/subuser/logic/subuserlib/builtInCommands/remove-old-images.py", line 37, in runCommand
    subuserlib.removeOldImages.removeOldImages(user=user,dryrun=options.dryrun,yes=options.yes,sourceRepo=repo,imageSourceName=options.imageSourceName)
  File "/home/timothy/current/subuser/logic/subuserlib/removeOldImages.py", line 23, in removeOldImages
    installedImagesThatAreInUse = getInstalledImagesThatAreInUse(user)
  File "/home/timothy/current/subuser/logic/subuserlib/removeOldImages.py", line 18, in getInstalledImagesThatAreInUse
    for inUseInstalledImage in subuser.getUser().getInstalledImages()[subuser.getImageId()].getImageLineage():
KeyError: 'sha256:ef69e4d69cd8041cc409132214e503eee440ac6bebb0724515e8e9dab7d521bb'
````

**Comment by timthelion** [comment]
https://github.com/subuser-security/subuser/commit/feb687fa92cfbede30f6297d32023e3733597d0c
