### ISSUE TITLE
Not a valid object name master

### ISSUE THREAD

**Issue by whoo** [subuser-security/subuser#320]
Hi Guys,
This Problem is still present. #277 
commit fd3b7db8c5c11046e192021c088d0a29cb3fcf09

You need to commit : 
initial file inside  ```~/.subuser/registry```
checkout master ~/.subuser/repositories/default, ```git checkout master```

#######
```rm -rf ~/.subuser``` then ```subuser list available```

```
Initial commit.
Cloning repository default from https://github.com/subuser-security/subuser-default-repository.git
Clonage dans '/home/domi/.subuser/repositories/default'...
remote: Counting objects: 2668, done.
remote: Total 2668 (delta 0), reused 0 (delta 0), pack-reused 2668
Réception d'objets: 100% (2668/2668), 334.88 KiB | 0 bytes/s, fait.
Résolution des deltas: 100% (1535/1535), fait.
Traceback (most recent call last):
  File "/usr/local/Wizz/subuser/bin//subuser", line 52, in <module>
    command(sys.argv[2:])
  File "/usr/local/Wizz/subuser/logic/subuserlib/builtInCommands/list.py", line 57, in runCommand
    reposToList = user.registry.repositories.keys()
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/user.py", line 70, in registry
    self.__registry.ensureGitRepoInitialized()
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/registry.py", line 63, in ensureGitRepoInitialized
    self.commit("Initial commit.",_no_lock_needed = True)
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/registry.py", line 106, in commit
    self.repositories.save()
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/registry.py", line 52, in repositories
    self.__repositories = repositories.Repositories(self.user)
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/repositories.py", line 28, in __init__
    self.reloadRepositoryLists()
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/repositories.py", line 76, in reloadRepositoryLists
    self.systemRepositories = loadRepositoryDict(subuserlib.loadMultiFallbackJsonConfigFile.getConfig(self.systemRepositoryListPaths))
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/repositories.py", line 74, in loadRepositoryDict
    repositories[repoName] = Repository(self.user,name=repoName,gitOriginURI=gitOriginURI,gitCommitHash=gitCommitHash,temporary=temporary,sourceDir=sourceDir)
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/repository.py", line 35, in __init__
    self.updateSources(initialUpdate=True)
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/repository.py", line 193, in updateSources
    if self.updateGitCommitHash():
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/repository.py", line 233, in updateGitCommitHash
    if self.gitRepository.getFileStructureAtCommit("master").exists("./.subuser.json"):
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/fileStructure.py", line 61, in exists
    return self._exists(path)
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/gitRepository.py", line 239, in _exists
    for object in self.lsTree():
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/gitRepository.py", line 169, in lsTree
    (returncode,output) = self.gitRepository.runCollectOutput(["ls-tree"]+args)
  File "/usr/local/Wizz/subuser/logic/subuserlib/classes/gitRepository.py", line 91, in runCollectOutput
    raise GitException(stderr)
subuserlib.classes.gitRepository.GitException: fatal: Not a valid object name master```

**Comment by timthelion** [comment]
Hi,

thanks for the bug report. Would you mind sharing with me the version of 
git that you're running. "master" does exist, and this works on my 
computer, but if I recal correctly, there was discussion of changing git 
to not clone all branches but only the default branch. If my assumption 
is correct, and this is due to that change in gits behavior, than I'm 
going to also need to know what flag I need to pass git to tell it to 
clone all branches. Then we can change the clone line and things should 
be fixed.

**Comment by whoo** [comment]
Hi Timothy,

You're probably right with git version (I'm not aware for that)
For example the default branch for ```~/.subuser/repositories/default``` is ```latest``` instead of ```master```.

```
cd ~/.subuser/repositories/default
git checkout master
```

ps: thanks for your work on amazing subuser !

**Comment by timthelion** [comment]
Does the line `git checkout master` that you show here work? If so, I'm confused.

What does `git version` say?

**Comment by timthelion** [comment]
I've uploaded a change to git. Can you please git pull and test if it helped?
