### ISSUE TITLE
Cannot start xpra on Fedora 25

### ISSUE THREAD

**Issue by colinemonds** [subuser-security/subuser#343]
Hello,

I'm trying to create a container for the proprietary software suite WPS Office. I am able to build the Ubuntu container successfully. Unfortunately, when I try to launch it on the Fedora 25 host, I get the message "Starting xpra server..." and then it hangs forever. [The subuser docs say](http://subuser.org/developers/common-tasks.html#debugging-the-xpra-bridge) that XPRA problems can be debugged by setting an environment variable, so here is the output for your pleasure:
```
cemonds:~/subuser-images$ SUBUSER_DEBUG_XPRA= subuser run wps-office
Starting xpra server...
xpra initialization error:
 failed to create the Xorg log directory '/home/subuser//.xpra': [Errno 13] Permission denied:
'/home/subuser//.xpra'
[Errno 13] Permission denied: '/home/subuser//.xpra'
Error: failed to write script file in '/home/subuser/.xpra':
 [Errno 13] Permission denied: '/home/subuser/.xpra'
Error trying to create XAUTHORITY file /home/subuser/.Xauthority: [Errno 13] Permission denied:
 '/home/subuser/.Xauthority'
```

There are no additional log files, not even in the directory that the docs name (~/.subuser/volumes/xpra/wps-office/xpra-home), even though the directory does get created. In case you want to try it yourself, the dockerfile is as such:
```
FROM ubuntu
RUN mkdir /usr/share/desktop-directories && echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true|debconf-set-selections && apt-get update && apt install -y wget xdg-utils apt-transport-https && wget http://kdl1.cache.wps.com/ksodl/download/linux/a21//wps-office_10.1.0.5707~a21_amd64.deb -O wpsoffice.deb && apt install -y ./wpsoffice.deb
```
and these are the permissions I set:
```
{
    "description":"WPS Office suite Alpha21"
    ,"maintainer":"-"
    ,"executable":"/usr/bin/wps"
    ,"gui":{"clipboard":true}
    ,"user-dirs":["Documents"]
    ,"sound-card":false
    ,"allow-network-access":false
    ,"basic-common-permissions":true
}
```

Thank you for your support and for developing this great software!

**Comment by unique-EJ** [comment]
Looks like a Unix file permissions issue. On Ubuntu 24.04.2, aarch64 Raspberry Pi 3, for me starting `xpra` - x11 bridge server - fails to create a directory.

If I `subuser run \!service-subuser-[software app]-xpra-server` (the subuser service for `xpra` server), this uses `sudo` and wants my host password for that container.

I can't run an app with `subuser` and that app uses `xpra`.

> Warning: failed to create script directory '/run/user/1000/xpra'

> cannot access python uinput module:
> ` `No module named 'uinput'
> ...

**Comment by shannara** [comment]
Hi similar issue on debian trixie (futur stable).
I work on new package for debian archive, sorry for delay i don't see bug open on debian, ubuntu :( 
i fix issue with python > 3.9 (thanks unique-EJ), other fix for docker API (need v1.24 instead v1.13) and update note for git config set, infact need explicit define defaultBranch to master

test on debian 12 work as well, but first entrance is unstable, when i test on it, not work with issue on xpra. 
For unknown reason when i try to debug inside xpra container, don't remember action i do, xpra client run after and xterm container run successfully 🤔, but can't reproduce after :(  

>
>user@debian-testing:~$ subuser run xterm
>Starting xpra server...
>^CTraceback (most recent call last):
>  File "/usr/bin/subuser", line 52, in <module>
>   command(sys.argv[2:])
>  File "/usr/lib/python3/dist-packages/subuserlib/builtInCommands/run.py", line 90, in runCommand
>    runtime.run(argParser.subuserArgs)
>  File "/usr/lib/python3/dist-packages/subuserlib/classes/subuserSubmodules/run/runtime.py", line 337, in run
>     return reallyRun()
>  File "/usr/lib/python3/dist-packages/subuserlib/classes/subuserSubmodules/run/runtime.py", line 309, in reallyRun 
>     self.subuser.x11Bridge.addClient()
>  File "/usr/lib/python3/dist-packages/subuserlib/classes/service.py", line 93, in addClient
>     serviceStatus = self.start(serviceStatus)
>  File "/usr/lib/python3/dist-packages/subuserlib/classes/subuserSubmodules/run/x11Bridge.py", line 245, in start
>     self.waitForContainerToLaunch("xpra is ready", serverProcess, suppressOutput)
>  File "/usr/lib/python3/dist-packages/subuserlib/classes/subuserSubmodules/run/x11Bridge.py", line 271, in waitForContainerToLaunch
        time.sleep(0.1)
>
>  KeyboardInterrupt

On docker logs for container xpra :

> Warning: failed to create script directory '/run/user/1000/xpra'
> [Errno 2] No such file or directory: '/run/user/1000/xpra'
> ($XDG_RUNTIME_DIR has not been created?)
> cannot access python uinput module:
>   No module named 'uinput'
> _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

**Comment by totaam** [comment]
@shannara see https://github.com/Xpra-org/xpra/issues/4383

**Comment by colinemonds** [comment]
Closed due to my own inactivity.

If anyone has the above issue again on Fedora, I suggest trying to disable SELinux enforcement and seeing if that helps. That would be a common problem with Docker in RHEL derivatives.
